﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using L2PAccess.API.Model;
using Refit;
using L2PAccess.Authentication.Model.Request;
using L2PAccess.Authentication.Model.Response;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace L2PAccess.API
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIL2PApi : IL2PApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIL2PApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<L2PResponse<Course>> ViewAllCourseInfo()
        {
            var arguments = new object[] {  };
            return (Task<L2PResponse<Course>>) methodImpls["ViewAllCourseInfo"](Client, arguments);
        }

        public virtual Task<L2PResponse<Course>> ViewCourseInfo(string courseId)
        {
            var arguments = new object[] { courseId };
            return (Task<L2PResponse<Course>>) methodImpls["ViewCourseInfo"](Client, arguments);
        }

    }
}

namespace L2PAccess.Authentication
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIRwthOauth : IRwthOauth
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIRwthOauth(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<Code> GetCode(CodeEndpointParams parameters)
        {
            var arguments = new object[] { parameters };
            return (Task<Code>) methodImpls["GetCode"](Client, arguments);
        }

        public virtual Task<Token> GetAccessToken(AccessTokenParams parameters)
        {
            var arguments = new object[] { parameters };
            return (Task<Token>) methodImpls["GetAccessToken"](Client, arguments);
        }

        public virtual Task<Token> GetRefreshToken(RefreshTokenParams parameters)
        {
            var arguments = new object[] { parameters };
            return (Task<Token>) methodImpls["GetRefreshToken"](Client, arguments);
        }

        public virtual Task<Token> InvalidateAccessToken(InvalidateTokenParams parameters)
        {
            var arguments = new object[] { parameters };
            return (Task<Token>) methodImpls["InvalidateAccessToken"](Client, arguments);
        }

        public virtual Task<Token> GetAccessTokenInfo(TokenEndpointParams parameters)
        {
            var arguments = new object[] { parameters };
            return (Task<Token>) methodImpls["GetAccessTokenInfo"](Client, arguments);
        }

    }
}


